CREATE TABLE IF NOT EXISTS OPERATOR_ROUTES(
ROUTE_ID varchar(10) NOT NULL,
DIRECTION integer NOT NULL,
STOP_ON_DIRECTION_NUMBER integer NOT NULL,
STOP_ID varchar(10),
PRIMARY KEY(ROUTE_ID, DIRECTION, STOP_ON_DIRECTION_NUMBER));

CREATE TABLE IF NOT EXISTS OPERATOR_STOPS(
STOP_ID VARCHAR(10) NOT NULL PRIMARY KEY.
NAME VARCHAR(100).
LON REAL.
LAT REAL.
COORDINATES_QUALITY INTEGER.
MORE_INFO TEXT);

CREATE TABLE IF NOT EXISTS OSM_STOPS(
NORMAL_STOP BIGINT,
STOP_POSITION BIGINT,
REF_ID VARCHAR(10) PRIMARY KEY NOT NULL,
NORMAL_STOP_NAME VARCHAR(255),
STOP_POSITION_NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS OSM_TREE(
RELATION_ID BIGINT PRIMARY KEY NOT NULL,
RELATION_PARENT BIGINT,
NAME VARCHAR(255),
TYPE VARCHAR(1),
ROUTE_ID VARCHAR(20),
FOREIGN KEY(RELATION_PARENT) REFERENCES OSM_TREE(RELATION_ID)
);

CREATE TABLE IF NOT EXISTS OSM_RELATIONS(
REF_ID VARCHAR(10) NOT NULL, PRIMARY KEY(RELATION_ID, REF_ID),
RELATION_ID BIGINT NOT NULL
);
